Repository iotexproject/iotex-core, pull requests merged in 2019-05, with the labels that each got.

#1109 ioctl account createadd supports overwrite #1103
  cli/ioctl/cmd/account/accountcreateadd.go
Labels: v0.5.2, v0.6.0

#1113 Modify ReadContract API
  api/api.go
  api/api_test.go
  cli/ioctl/cmd/action/action.go
  proto/api/api.proto
  protogen/iotexapi/api.pb.go
  tools/executiontester/blockchain/contract.go
Labels: api, breaking change, v0.6.0

#1108 Cleanup native voting system code #1071 second batch
  action/action.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  action/protocol/poll/protocol.go
  action/protocol/vote/protocol.go
  action/vote.go
  blockchain/block/block_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockdao_test.go
  blockchain/blockvalidator_test.go
  blocksync/blocksync_test.go
  blocksync/buffer_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/subchain_test.go
  e2etest/bigint_test.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  gasstation/gasstattion_test.go
  indexservice/indexer.go
  indexservice/indexer_test.go
  proto/types/action.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/action.pb.go
  server/itx/server.go
  state/factory/factory_test.go
  testutil/signedaction.go
  testutil/signedaction_test.go
  tools/minicluster/minicluster.go
  tools/util/injectorutil.go
Labels: breaking change, v0.6.0

#1128 Remove signing step for ReadContract() calls
  api/api_test.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionclaim.go
  cli/ioctl/cmd/action/actiondeploy.go
  cli/ioctl/cmd/action/actiondeposit.go
  cli/ioctl/cmd/action/actioninvoke.go
  cli/ioctl/cmd/action/actionread.go
  cli/ioctl/cmd/action/actiontransfer.go
  tools/executiontester/blockchain/contract.go
Labels: v0.6.0

#1144 Remove pkg/keypair, switch to go-pkgs/crypto
  Gopkg.lock
  Gopkg.toml
  action/actctx.go
  action/action.go
  action/builder.go
  action/createdeposit.go
  action/execution.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/datamodel.go
  action/putblock.go
  action/putpollresult.go
  action/settledeposit.go
  action/startsubchain.go
  action/transfer.go
  blockchain/block/builder.go
  blockchain/block/header.go
  blockchain/block/runnable.go
  blockchain/block/testing.go
  blockchain/block/testing_test.go
  blockchain/blockchain_test.go
  blockchain/blockdao_test.go
  blockchain/blockvalidator.go
  blockchain/blockvalidator_test.go
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountcreate.go
  cli/ioctl/cmd/action/actionhash.go
  config/config.go
  config/config_test.go
  consensus/scheme/rolldpos/rolldpos.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/rolldpos/subchain.go
  crypto/README.md
  e2etest/bigint_test.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/local_transfer_test.go
  e2etest/rewarding_test.go
  endorsement/endorsement.go
  pkg/keypair/keypair_test.go
  pkg/keypair/secp256k1_test.go
  state/factory/factory_test.go
  test/identityset/identityset.go
  test/testaddress/testaddress.go
  testutil/signedaction.go
  tools/actioninjector.v2/internal/cmd/random.go
  tools/addrgen/internal/cmd/createconfig.go
  tools/addrgen/internal/cmd/generate.go
  tools/executiontester/blockchain/contract.go
  tools/executiontester/blockchain/stable_token.go
  tools/executiontester/executiontester.go
  tools/minicluster/minicluster.go
  tools/util/injectorutil.go
  vendor/github.com/iotexproject/go-pkgs/crypto/key.go
  vendor/github.com/iotexproject/go-pkgs/crypto/secp256k1.go
Labels: v0.6.0

#1141 Fix the bugs of double charging gas fee
  action/protocol/account/protocol.go
  action/protocol/account/protocol_test.go
  action/protocol/account/transfer.go
  action/protocol/account/transfer_test.go
  action/protocol/execution/evm/evm.go
  action/protocol/execution/evm/evm_test.go
  action/protocol/execution/protocol.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  actpool/actpool_test.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockvalidator_test.go
  blockchain/genesis/genesis.go
  blocksync/blocksync_test.go
  blocksync/buffer_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  e2etest/bigint_test.go
  e2etest/local_test.go
  gasstation/gasstattion_test.go
  server/itx/server.go
  state/factory/factory_test.go
Labels: breaking change, v0.6.0

#1135 refine precommit behavior
  consensus/consensusfsm/context.go
  consensus/consensusfsm/fsm.go
  consensus/consensusfsm/fsm_test.go
  consensus/consensusfsm/mock_context_test.go
  consensus/scheme/rolldpos/endorsementmanager.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/rolldpos/roundctx.go
  e2etest/rewarding_test.go
Labels: enhancement, v0.6.0

#1178 add unit test for new multisend contract
  action/protocol/execution/protocol_test.go
  action/protocol/execution/testdata/multisend2.json
  action/protocol/execution/testdata/multisend2.sol
Labels: v0.6.0

#1181 repair nightly build go mod
  .circleci/config.yml
Labels: v0.6.0

#1189 Improve consensus metrics
  consensus/consensusfsm/fsm.go
  consensus/scheme/rolldpos/rolldposctx.go
  go.mod
Labels: v0.6.0

#1190 Update iote-election to 0.1.10
  go.mod
  go.sum
Labels: v0.6.0

#1187 Fix contract read return ni by setting correct nonce and gas limit in…
  api/api.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  chainservice/chainservice.go
  gasstation/gasstattion.go
  gasstation/gasstattion_test.go
  tools/actioninjector.v2/internal/client/client_test.go
Labels: v0.6.0

#1184 Implement block streaming API
  api/api.go
  api/blocklistener.go
  consensus/consensusfsm/mock_context_test.go
  e2etest/local_test.go
  go.mod
  go.sum
  tools/actioninjector.v2/internal/client/client_test.go
Labels: v0.6.0

#1202 Revert breaking changes
  action/protocol/account/util/util.go
  action/protocol/poll/protocol.go
Labels: v0.6.1

#1203 Update sanity check for API range queries
  api/api.go
  api/api_test.go
Labels: v0.6.1

#1206 Update api test client interface
  api/apitestclient.go
  test/mock/mock_apiserviceclient/mock_apiserviceclient.go
Labels: v0.6.2

#1214 Update pacific block height
  blockchain/genesis/genesis.go
Labels: v0.6.2, v0.7.0

#1204 Ioctl should allow import/export from to keystore file #1191
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountimport.go
  go.mod
Labels: v0.6.2, v0.7.0

#1212 Remove testaddress #1188
  action/action_test.go
  action/builder_test.go
  action/createdeposit_test.go
  action/execution_test.go
  action/protocol/account/protocol_test.go
  action/protocol/account/transfer_test.go
  action/protocol/execution/evm/contract_test.go
  action/protocol/execution/evm/evm_test.go
  action/protocol/execution/protocol_test.go
  action/protocol/generic_validator_test.go
  action/protocol/multichain/mainchain/createdeposit_test.go
  action/protocol/multichain/mainchain/datamodel_test.go
  action/protocol/multichain/mainchain/protocol_test.go
  action/protocol/multichain/mainchain/putblock_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  action/protocol/multichain/mainchain/stopsubchain_test.go
  action/protocol/multichain/subchain/protocol_test.go
  action/protocol/poll/protocol_test.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward_test.go
  action/putblock_test.go
  action/putpollresult_test.go
  action/settledeposit_test.go
  action/transfer_test.go
  actpool/actioniterator/actioniterator_test.go
  actpool/actpool_test.go
  api/api_test.go
  blockchain/block/block_test.go
  blockchain/block/body_test.go
  blockchain/block/builder_test.go
  blockchain/block/footer_test.go
  blockchain/block/header_test.go
  blockchain/block/testing_test.go
  blockchain/blockchain_test.go
  blockchain/blockdao_test.go
  blockchain/blockvalidator_test.go
  blocksync/blocksync_test.go
  blocksync/buffer_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/subchain_test.go
  e2etest/bigint_test.go
  e2etest/local_test.go
  e2etest/util.go
  gasstation/gasstattion_test.go
  state/candidate_test.go
  state/factory/factory_test.go
  test/identityset/identityset.go
  test/testaddress/testaddress.go
  testutil/signedaction_test.go
  tools/actioninjector.v2/internal/client/client_test.go
Labels: v0.7.0

#1216 ioctl action transfer uses IOTX for amount rather than Rau #1215
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/util/util.go
Labels: v0.6.2, v0.7.0
