Repository iotexproject/iotex-core, pull requests merged in 2019-03, with the labels that each got.

#647 update election package
  Gopkg.lock
  Gopkg.toml
  blockchain/genesis/genesis.go
  chainservice/chainservice.go
  config/config.go
  vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
  vendor/github.com/iotexproject/iotex-election/committee/committee.go
  vendor/github.com/iotexproject/iotex-election/contract/register.abi
  vendor/github.com/iotexproject/iotex-election/contract/register.go
  vendor/github.com/iotexproject/iotex-election/contract/staking.abi
  vendor/github.com/iotexproject/iotex-election/contract/staking.go
Labels: breaking change

#632 IOTEX-275 Get rid of old genesis completely
  Dockerfile
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  action/protocol/poll/protocol.go
  action/protocol/vote/protocol.go
  api/api.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockdao.go
  blockchain/genesis.go
  blockchain/genesis/genesis.go
  blockchain/genesis/genesis_test.go
  blockchain/genesis_test.go
  blockchain/testnet_actions.yaml
  config/config.go
  consensus/scheme/rolldpos/rolldposctx.go
  e2etest/local_test.go
  e2etest/multichain_test.go
  e2etest/util.go
  explorer/explorer.go
  explorer/explorer_test.go
  proto/types/blockchain.proto
  protogen/iotextypes/action.pb.go
  protogen/iotextypes/blockchain.pb.go
  server/itx/server.go
  server/itx/subchain.go
  tools/minicluster/minicluster.go
  tools/minicluster/testnet_actions.yaml
Labels: breaking change

#651 Fix make reboot and run
  e2etest/config_local_delegate.yaml
Labels: 0.5.0-rc3

#648 IOTEX-291 Using sha3 instead of blake
  Gopkg.lock
  action/action.go
  action/protocol/execution/protocol_test.go
  api/api_test.go
  beacon/beacon.go
  beacon/beacon_test.go
  blockchain/block/block_test.go
  blockchain/block/header.go
  crypto/benchmark_test.go
  crypto/cryptosort.go
  crypto/cryptosort_test.go
  crypto/merkle.go
  crypto/merkle_test.go
  db/trie/trie.go
  db/trie/trie_test.go
  endorsement/endorsement.go
  pkg/hash/hash.go
  pkg/keypair/keypair.go
  pkg/keypair/keypair_test.go
  vendor/github.com/golang/mock/mockgen/model/model.go
Labels: 0.5.0-rc3

#654 Change keypair.PrivateKey/PublicKey to interface
  action/actctx.go
  action/action.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/datamodel.go
  action/protocol/multichain/mainchain/stopsubchain.go
  action/protocol/vote/protocol.go
  action/putpollresult_test.go
  actpool/actioniterator/actioniterator.go
  actpool/actpool.go
  address/address_v1_test.go
  api/api.go
  api/api_test.go
  blockchain/block/block.go
  blockchain/block/block_test.go
  blockchain/block/builder.go
  blockchain/block/header.go
  blockchain/block/testing.go
  blockchain/blockchain.go
  blockchain/blockdao.go
  blockchain/blockvalidator.go
  blockchain/indexbuilder.go
  cli/ioctl/cmd/account/accountcreate.go
  cli/ioctl/cmd/account/accountimport.go
  cli/ioctl/cmd/action/actiontransfer.go
  config/config.go
  config/config_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/rolldposctx_test.go
  consensus/scheme/rolldpos/subchain.go
  consensus/scheme/rolldpos/subchain_test.go
  crypto/benchmark_test.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/local_transfer_test.go
  e2etest/multichain_test.go
  e2etest/rewarding_test.go
  endorsement/endorsement.go
  explorer/explorer.go
  explorer/explorer_test.go
  explorer/gasstattion.go
  gasstation/gasstattion.go
  indexservice/indexer.go
  indexservice/indexer_test.go
  pkg/keypair/keypair.go
  pkg/keypair/keypair_test.go
  pkg/keypair/secp256k1.go
  pkg/keypair/secp256k1_test.go
  state/factory/statetx.go
  state/factory/workingset.go
  test/identityset/identityset.go
  test/testaddress/testaddress.go
  tools/actioninjector.v2/internal/cmd/random.go
  tools/addrgen/internal/cmd/createconfig.go
  tools/addrgen/internal/cmd/generate.go
  tools/minicluster/minicluster.go
  tools/util/injectorutil.go
Labels: 0.5.0-rc3

#652 Rename BP display method name in API
  action/protocol/poll/protocol.go
  api/api_test.go
Labels: 0.5.0-rc3

#662 update Gopkg.toml and update dependencies
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
  vendor/github.com/iotexproject/iotex-election/committee/committee.go
  vendor/github.com/iotexproject/iotex-election/pb/election/election.pb.go
  vendor/github.com/iotexproject/iotex-election/pb/election/election.proto
  vendor/github.com/iotexproject/iotex-election/types/candidate.go
  vendor/github.com/iotexproject/iotex-election/types/resultcalculator.go
Labels: 0.5.0-rc3, breaking change

#656 IOTEX-275 Separate committee system config and genesis config
  blockchain/genesis/genesis.go
  chainservice/chainservice.go
  config/config.go
  server/itx/server.go
Labels: 0.5.0-rc3, breaking change

#670 Change beacon to gravity and fix one poll config bug
  action/protocol/poll/protocol.go
  action/putpollresult.go
  blockchain/blockchain.go
  blockchain/genesis/genesis.go
  chainservice/chainservice.go
  server/itx/server.go
Labels: 0.5.0-rc3, breaking change

#677 IOTEX-276 Make polling pending actions get rid of expired actions and refactor actpool code
  action/protocol/multichain/mainchain/protocol_test.go
  actpool/actpool.go
  actpool/actpool_test.go
  config/config.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/local_transfer_test.go
  test/mock/mock_actpool/mock_actpool.go
  tools/minicluster/minicluster.go
Labels: 0.5.0-rc3

#679 IOTEX-279 Add GetProductivity API for BPs
  api/api.go
  api/api_test.go
  proto/api/api.proto
  protogen/iotexapi/api.pb.go
Labels: 0.5.0-rc3

#700 Add GetServerMeta() API, get package information from git
  Makefile
  api/api.go
  pkg/version/version.go
  proto/api/api.proto
  proto/types/node.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/node.pb.go
Labels: 0.5.0-rc4

#708 fix invalid balance output for ioctl
  cli/ioctl/cmd/account/accountbalance.go
  cli/ioctl/util/util.go
  cli/ioctl/util/util_test.go
Labels: 0.5.0-rc4, invalid

#713 IOTEX-316 silent private key importing for ioctl
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountimport.go
Labels: 0.5.0-rc4

#696 Move GravityChainHeightInterval to genesis
  blockchain/genesis/genesis.go
  chainservice/chainservice.go
Labels: 0.5.0-rc4, breaking change

#721 IOTEX-322 Add claim cmd and remove productivity cmd for ioctl
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionclaim.go
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/node/node.go
  cli/ioctl/cmd/node/nodedelegate.go
  cli/ioctl/cmd/node/nodeproductivity.go
  cli/ioctl/cmd/node/nodereward.go
Labels: 0.5.0-rc4

#698 IOTEX-302 Improve index storage efficiency and remove stale indexing code
  action/protocol/execution/protocol_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockdao.go
  blockchain/blockdao_test.go
  blockchain/indexbuilder.go
  explorer/explorer.go
  explorer/explorer_test.go
  explorer/idl/explorer.idl
  explorer/idl/explorer/explorer.go
  protogen/iotexrpc/rpc.pb.go
  test/mock/mock_blockchain/mock_blockchain.go
  test/mock/mock_explorer/mock_explorer.go
Labels: 0.5.0-rc4, breaking change

#719 IOTEX-272 Avoid passing remaining block gas as a pointer in run action context
  action/protocol/account/protocol.go
  action/protocol/account/protocol_test.go
  action/protocol/account/transfer.go
  action/protocol/account/transfer_test.go
  action/protocol/context.go
  action/protocol/execution/evm/contract_test.go
  action/protocol/execution/evm/evm.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/createdeposit_test.go
  action/protocol/multichain/mainchain/putblock_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  action/protocol/vote/protocol.go
  action/protocol/vote/protocol_test.go
  actpool/actpool_test.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockvalidator_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  explorer/explorer_test.go
  state/factory/factory_test.go
  state/factory/statetx.go
  state/factory/workingset.go
Labels: 0.5.0-rc4

#722 IOTEX-328 Add the exempt address list from epoch reward
  action/protocol/rewarding/admin.go
  action/protocol/rewarding/admin_test.go
  action/protocol/rewarding/fund_test.go
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
  action/protocol/rewarding/rewardingpb/rewarding.pb.go
  action/protocol/rewarding/rewardingpb/rewarding.proto
  blockchain/blockchain.go
  blockchain/genesis/genesis.go
Labels: 0.5.0-rc4

#724 IOTEX-316 Add more version info and rewrite version cmd for ioctl
  Makefile
  api/api.go
  cli/ioctl/cmd/version/version.go
  pkg/version/version.go
  proto/types/node.proto
  protogen/iotextypes/node.pb.go
  server/main.go
Labels: 0.5.0-rc4

#709 Iotex 247 remove block container wrap in protobuf definition
  .gitignore
  blocksync/blocksync.go
  coverage.txt
  dispatcher/dispatcher.go
  dispatcher/dispatcher_test.go
  proto/rpc/rpc.proto
  protogen/iotexrpc/rpc.pb.go
  protogen/utils.go
Labels: 0.5.0-rc4

#732 IOTEX-331 Bounce up protoc-gen-go to 1.3.0 and regenerate the files
  Gopkg.lock
  Gopkg.toml
  action/protocol/account/accountpb/account.pb.go
  action/protocol/multichain/mainchain/mainchainpb/mainchain.pb.go
  action/protocol/multichain/subchain/subchainpb/subchain.pb.go
  action/protocol/poll/pollpb/poll.pb.go
  action/protocol/rewarding/rewardingpb/rewarding.pb.go
  db/trie/triepb/trie.pb.go
  p2p/pb/message.pb.go
  protogen/iotexapi/api.pb.go
  protogen/iotexrpc/rpc.pb.go
  protogen/iotextypes/action.pb.go
  protogen/iotextypes/blockchain.pb.go
  protogen/iotextypes/endorsement.pb.go
  protogen/iotextypes/genesis.pb.go
  protogen/iotextypes/node.pb.go
  protogen/testingpb/testing.pb.go
  tools/executiontester/blockchain/contract.go
  tools/executiontester/blockchain/fp_token.go
  tools/executiontester/blockchain/stable_token.go
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.proto
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.proto
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.proto
Labels: 0.5.0-rc4

#725 IOTEX-302 Enable index and api service if a node start as a gateway
  Makefile
  action/protocol/execution/protocol_test.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  chainservice/chainservice.go
  config/config.go
  e2etest/config_local_delegate.yaml
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/local_transfer_test.go
  e2etest/multichain_test.go
  explorer/explorer_test.go
  server/itx/subchain_test.go
  tools/actioninjector.v2/internal/client/client_test.go
  tools/executiontester/executiontester.go
  tools/minicluster/minicluster.go
Labels: 0.5.0-rc4, breaking change

#684 IOTEX-124 Add state recovery tool in case of blockchain start failure
  Makefile
  README.md
  blockchain/blockchain.go
  tools/staterecoverer/staterecoverer.go
Labels: 0.5.0-rc4

#738 upgrade iotex-election to a747189bfbbd761f66dd3df92a346f14471da5b1
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
  vendor/github.com/iotexproject/iotex-election/committee/committee.go
  vendor/github.com/iotexproject/iotex-election/pb/election/election.pb.go
  vendor/github.com/iotexproject/iotex-election/pb/election/election.proto
  vendor/github.com/iotexproject/iotex-election/types/result.go
  vendor/github.com/iotexproject/iotex-election/types/resultcalculator.go
  vendor/github.com/iotexproject/iotex-election/types/vote.go
Labels: breaking change

#706 IOTEX-317 Error shouldn't been thrown when the failure receipt is returned
  action/protocol/execution/evm/evm.go
  action/protocol/execution/evm/evm_test.go
Labels: 0.5.0-rc4

#740 Remove admin and its operations from rewarding protocol
  action/action.go
  action/protocol/rewarding/admin.go
  action/protocol/rewarding/admin_test.go
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/rewardingpb/rewarding.pb.go
  action/protocol/rewarding/rewardingpb/rewarding.proto
  action/rewardmsg_test.go
  action/setreward.go
  blockchain/blockchain.go
  blockchain/genesis/genesis.go
  blockchain/genesis/genesis_test.go
  proto/types/action.proto
  protogen/iotextypes/action.pb.go
  tools/staterecoverer/staterecoverer.go
Labels: 0.5.0-rc4, breaking change

#741 Move rpc message type definitions into proto file
  dispatcher/dispatcher.go
  p2p/agent.go
  p2p/pb/message.pb.go
  p2p/pb/message.proto
  proto/rpc/rpc.proto
  protogen/iotexrpc/rpc.pb.go
  protogen/utils.go
  tools/actioninjector.v2/internal/client/client_test.go
Labels: 0.5.0-rc4, breaking change

#742 Issues: Support install ioctl built from master HEAD #715
  .circleci/config.yml
  install-cli.sh
Labels: 0.5.0-rc5

#743 IOTEX-185 log errors for write operation in stateDB
  action/protocol/execution/evm/contract_test.go
  action/protocol/execution/evm/evm.go
  action/protocol/execution/evm/evmstatedbadapter.go
  action/protocol/execution/evm/evmstatedbadapter_test.go
Labels: 0.5.0-rc5

#754 Fix two bugs in API
  action/protocol/poll/protocol.go
  api/api.go
Labels: 0.5.0-rc5

#753 Support windows for ioctl
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountdelete.go
  cli/ioctl/cmd/account/accountimport.go
  cli/ioctl/cmd/account/accountupdate.go
  cli/ioctl/cmd/action/action.go
  pkg/log/log.go
  pkg/log/redirectStderr_notwindows.go
  pkg/log/redirectStderr_windows.go
Labels: 0.5.0-rc5

#764 Fix version cmd output when failed to get server version
  cli/ioctl/cmd/version/version.go
Labels: 0.5.0-rc5

#763 Add ioctl target and add version info in buildcli.sh
  Makefile
  cli/ioctl/buildcli.sh
Labels: 0.5.0-rc5

#773 IOTEX-348 Add update cmd for ioctl
  cli/ioctl/README.md
  cli/ioctl/cmd/root.go
  cli/ioctl/cmd/update/update.go
Labels: 0.5.0-rc5

#776 fix two bugs in consensus
  blockchain/blockchain.go
  consensus/scheme/rolldpos/rolldposctx.go
Labels: 0.5.0-rc5

#770 IOTEX-349 Reenable unit tests of ReadActiveBlockProducersByHeight and ReadCommitteeBlockProducersByHeight
  action/protocol/poll/protocol.go
  action/protocol/poll/protocol_test.go
  api/api_test.go
  server/itx/server.go
Labels: 0.5.0-rc5

#775 IOTEX-308 Add a gas price threshold and make default be 1 qev
  action/protocol/multichain/mainchain/protocol_test.go
  actpool/actpool.go
  actpool/actpool_test.go
  api/api_test.go
  blockchain/blockchain_test.go
  config/config.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/local_transfer_test.go
  e2etest/util.go
  explorer/explorer_test.go
  testutil/gas.go
  tools/actioninjector.v2/internal/cmd/random.go
  tools/minicluster/minicluster.go
  tools/util/injectorutil.go
Labels: 0.5.0-rc5

#762 hotfix election out of boundary issue (#760)
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
Labels: 0.5.0-rc5

#778 Name auto-match for ioctl
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/action/actioninvoke.go
  cli/ioctl/cmd/node/nodedelegate.go
Labels: 0.5.0-rc5

#780 remove extra error output
  cli/ioctl/cmd/action/action.go
Labels: 0.5.0-rc5

#782 use time.Time as block time
  action/protocol/context.go
  action/protocol/execution/evm/evm.go
  action/protocol/execution/protocol_test.go
  api/api_test.go
  blockchain/block/block.go
  blockchain/block/block_test.go
  blockchain/block/header.go
  blockchain/block/runnable.go
  blockchain/block/testing.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockvalidator_test.go
  blocksync/blocksync_test.go
  blocksync/buffer_test.go
  consensus/consensus.go
  consensus/scheme/rolldpos/rolldpos.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/rolldpos/subchain_test.go
  e2etest/local_test.go
  e2etest/util.go
  explorer/explorer_test.go
  indexservice/indexer_test.go
  server/itx/server.go
  test/mock/mock_blockchain/mock_blockchain.go
  testutil/timestamp.go
Labels: 0.5.0-rc5

#777 IOTEX-352 Support foundation bonus and slash epoch reward when bad productivity
  action/protocol/protocol.go
  action/protocol/rewarding/admin.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
  action/protocol/rewarding/rewardingpb/rewarding.pb.go
  action/protocol/rewarding/rewardingpb/rewarding.proto
  api/api.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/genesis/genesis.go
  blockchain/genesis/genesis_test.go
  proto/types/genesis.proto
  protogen/iotextypes/genesis.pb.go
  test/mock/mock_blockchain/mock_blockchain.go
  test/mock/mock_chainmanager/mock_chainmanager.go
  test/mock/mock_factory/mock_workingset.go
Labels: 0.5.0-rc5

#746 IOTEX-307 Use LRU cache to keep some blocks in memory
  Gopkg.lock
  Gopkg.toml
  blockchain/blockchain.go
  blockchain/blockdao.go
  blockchain/blockdao_test.go
  config/config.go
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
Labels: 0.5.0-rc5

#795 IOTEX-358 Fix pulling delegate productivity
  blockchain/blockchain.go
Labels: breaking change, hotfix

#796 fix producing lock endorsement on nil
  action/protocol/execution/evm/evm.go
  consensus/scheme/rolldpos/rolldposctx.go
  dispatcher/dispatcher.go
Labels: hotfix

#798 Make P2P care about the messages from the honest nodes using the same genesis
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  p2p/agent.go
  p2p/agent_test.go
  server/itx/server.go
Labels: breaking change, bug

#813 Add action hash and status to transfer receipt and vote receipt
  action/protocol/account/transfer.go
  action/protocol/vote/protocol.go
  api/api_test.go
Labels: breaking change

#817 fix grpc cli reflection
  Makefile
  proto/api/api.proto
  proto/types/blockchain.proto
  proto/types/consensus.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/blockchain.pb.go
  protogen/iotextypes/consensus.pb.go
Labels: 0.5.0-rc6

#815 Use epochStartHeigh to sort delegate list when calculating productivity
  action/protocol/account/transfer.go
  action/protocol/poll/protocol.go
  action/protocol/vote/protocol.go
Labels: 0.5.0-rc6, breaking change

#821 Fix the block reward destination
  action/protocol/registry.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
  api/api_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  e2etest/local_transfer_test.go
  e2etest/rewarding_test.go
Labels: 0.5.0-rc6, breaking change

#820 delete redundant and wrong proposer checking
  consensus/scheme/rolldpos/rolldposctx.go
Labels: bug, hotfix

#826 Handle empty reward address and fix available balance acccounting
  action/protocol/rewarding/admin.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
Labels: 0.5.0-rc6, breaking change

#827 remove CreationHeight and LastUpdateHeight from Candidate
  action/protocol/vote/candidatesutil/candidatesutil.go
  consensus/consensus.go
  explorer/explorer.go
  explorer/idl/explorer.idl
  explorer/idl/explorer/explorer.go
  proto/types/action.proto
  protogen/iotextypes/action.pb.go
  state/candidate.go
Labels: 0.5.0-rc6, breaking change

#832 Point server out when print version for ioctl
  cli/ioctl/cmd/version/version.go
Labels: 0.5.0-rc6

#836 Improve hash cmd for ioctl
  cli/ioctl/cmd/action/actionhash.go
Labels: 0.5.0-rc6

#831 Add GetEpochData API
  api/api.go
  api/api_test.go
  cli/ioctl/cmd/node/nodedelegate.go
  proto/api/api.proto
  protogen/iotexapi/api.pb.go
Labels: 0.5.0-rc6, breaking change

#838 IOTEX-361 Fix error when granting epoch reward
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/reward.go
Labels: 0.5.0-rc6, breaking change

#835 rebroadcast precommit endorsement on timeout
  config/config.go
  consensus/consensusfsm/fsm.go
  consensus/consensusfsm/fsm_test.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/rolldpos/roundctx.go
  consensus/scheme/rolldpos/roundctx_test.go
  tools/minicluster/minicluster.go
Labels: 0.5.0-rc6, breaking change

#841 IOTEX-363 Add numActions to GetAccount API
  api/api.go
  api/api_test.go
  blockchain/blockchain.go
  consensus/consensusfsm/mock_context_test.go
  proto/types/blockchain.proto
  protogen/iotextypes/blockchain.pb.go
  test/mock/mock_blockchain/mock_blockchain.go
  tools/actioninjector.v2/internal/client/client_test.go
Labels: breaking change

#864 Fix P2P and blocksync efficiency (part 1)
  Gopkg.lock
  Gopkg.toml
  blocksync/blocksync.go
  blocksync/worker.go
  config/config.go
  p2p/agent.go
  vendor/github.com/iotexproject/go-p2p/p2p.go
Labels: v0.5.0-rc7

#883 Fix block cmd
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/bc/bcblock.go
Labels: invalid

#876 Print new account(s) in JSON format
  cli/ioctl/cmd/account/accountcreate.go
Labels: bettereng

#889 Sort alias list when print
  cli/ioctl/cmd/alias/aliaslist.go
Labels: enhancement

#893 Query upcoming delegates for ioctl
  cli/ioctl/cmd/node/node.go
  cli/ioctl/cmd/node/nodedelegate.go
Labels: enhancement
