Repository iotexproject/iotex-core, pull requests merged in 2019-04, with the labels that each got.

#911 Add export cmd for ioctl
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountexport.go
Labels: enhancement

#913 Update usage of ioctl
  cli/ioctl/cmd/node/nodedelegate.go
  cli/ioctl/cmd/update/update.go
Labels: enhancement

#896 Add multisend bytecode generator
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/util/util.go
  cli/tools/multisend/multisend.go
Labels: enhancement

#895 Filter empty and duplicate peer ID when retrieving neighbors
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/iotexproject/go-p2p/p2p.go
Labels: v0.5.0-rc8

#892 Blocksync efficiency (Part 2): improving block request scheduling
  blocksync/worker.go
  config/config.go
Labels: v0.5.0-rc8

#914 IOTEX-385 Expose reward details via log
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
  action/protocol/rewarding/rewardingpb/rewarding.pb.go
  action/protocol/rewarding/rewardingpb/rewarding.proto
  e2etest/local_test.go
  e2etest/util.go
Labels: breaking change, v0.5.0-rc8

#919 split block storage
  api/api_test.go
  blockchain/block/block.go
  blockchain/block/block_test.go
  blockchain/block/body.go
  blockchain/block/builder.go
  blockchain/block/footer.go
  blockchain/block/header.go
  blockchain/block/testing.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockdao.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/roundcalculator.go
  consensus/scheme/rolldpos/subchain_test.go
  e2etest/rewarding_test.go
  explorer/explorer.go
  indexservice/indexer_test.go
  pkg/cache/threadsafelrucache.go
  proto/types/blockchain.proto
  protogen/iotextypes/blockchain.pb.go
  server/itx/server.go
  test/mock/mock_blockchain/mock_blockchain.go
Labels: breaking change, v0.5.0-rc8

#921 Shrink ioctl binary
  Makefile
Labels: bettereng

#922 upgrade iotex-election package to v0.1.6
  Gopkg.lock
  Gopkg.toml
  chainservice/chainservice.go
  config/config.go
  vendor/github.com/iotexproject/iotex-election/committee/committee.go
  vendor/github.com/iotexproject/iotex-election/db/kvstore.go
  vendor/github.com/iotexproject/iotex-election/test/mock/mock_committee/mock_committee.go
  vendor/github.com/iotexproject/iotex-election/types/candidate.go
  vendor/github.com/iotexproject/iotex-election/types/result.go
Labels: breaking change, v0.5.0-rc8

#842 Return not found even if it's deleted in the current transaction
  db/kvstore4trie.go
  db/kvstore4trie_test.go
  state/factory/factory_test.go
  state/factory/statetx.go
Labels: v0.5.0-rc8

#920 New error handling for ioctl
  cli/ioctl/cmd/account/accountbalance.go
  cli/ioctl/cmd/account/accountcreate.go
  cli/ioctl/cmd/account/accountcreateadd.go
  cli/ioctl/cmd/account/accountdelete.go
  cli/ioctl/cmd/account/accountexport.go
  cli/ioctl/cmd/account/accountimport.go
  cli/ioctl/cmd/account/accountlist.go
  cli/ioctl/cmd/account/accountnonce.go
  cli/ioctl/cmd/account/accountupdate.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionclaim.go
  cli/ioctl/cmd/action/actiondeploy.go
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/action/actioninvoke.go
  cli/ioctl/cmd/action/actiontransfer.go
  cli/ioctl/cmd/alias/alias_test.go
  cli/ioctl/cmd/alias/aliasremove.go
  cli/ioctl/cmd/alias/aliasset.go
  cli/ioctl/cmd/bc/bcblock.go
  cli/ioctl/cmd/bc/bcinfo.go
  cli/ioctl/cmd/config/config.go
  cli/ioctl/cmd/config/configsetget.go
  cli/ioctl/cmd/node/nodedelegate.go
  cli/ioctl/cmd/node/nodereward.go
  cli/ioctl/cmd/root.go
  cli/ioctl/cmd/update/update.go
  cli/ioctl/cmd/version/version.go
  cli/ioctl/util/util.go
Labels: bettereng

#924 IOTEX-386 Add block hash and height into receipt
  action/protocol/account/transfer.go
  action/protocol/execution/evm/evm.go
  action/protocol/execution/evm/evm_test.go
  action/protocol/execution/evm/evmstatedbadapter.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/createdeposit.go
  action/protocol/multichain/mainchain/createdeposit_test.go
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/reward.go
  action/protocol/vote/protocol.go
  action/receipt.go
  api/api.go
  api/api_test.go
  blockchain/blockdao.go
  blockchain/blockdao_test.go
  blockchain/indexbuilder.go
  cli/ioctl/cmd/action/actionhash.go
  e2etest/rewarding_test.go
  explorer/explorer.go
  indexservice/indexer_test.go
  proto/api/api.proto
  proto/types/action.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/action.pb.go
  tools/executiontester/blockchain/contract.go
Labels: breaking change, v0.5.0-rc8

#932 Add blkhash in action hash cmd
  cli/ioctl/cmd/action/actionhash.go
Labels: enhancement, v0.5.0-rc8

#933 fix caching bug
  blockchain/blockdao.go
Labels: hotfix, v0.5.0-rc8

#950 IOTEX-391 Solve the linux libsect283k1_ubuntu.so error and support windows
  Makefile
  crypto/lib/benchmark_test.go
  crypto/lib/ec283.go
  crypto/lib/ec283_test.go
  install-cli.sh
Labels: bettereng, enhancement

#947 Update buildcli.sh
  cli/ioctl/buildcli.sh
Labels: enhancement

#934 Action hash cmd supports putpollresult action
  cli/ioctl/cmd/action/actionhash.go
Labels: enhancement, invalid, ioctl

#964 Add height info into grant reward
  action/createdeposit.go
  action/grantreward.go
  action/rewardmsg_test.go
  blockchain/blockchain.go
  e2etest/rewarding_test.go
  proto/types/action.proto
  protogen/iotextypes/action.pb.go
  test/mock/mock_blockchain/mock_blockchain.go
Labels: 0.5.0-rc9, breaking change

#972 Fix stderr error
  cli/ioctl/cmd/account/accountbalance.go
  cli/ioctl/cmd/account/accountcreate.go
  cli/ioctl/cmd/account/accountcreateadd.go
  cli/ioctl/cmd/account/accountdelete.go
  cli/ioctl/cmd/account/accountexport.go
  cli/ioctl/cmd/account/accountimport.go
  cli/ioctl/cmd/account/accountlist.go
  cli/ioctl/cmd/account/accountnonce.go
  cli/ioctl/cmd/account/accountupdate.go
  cli/ioctl/cmd/action/actionclaim.go
  cli/ioctl/cmd/action/actiondeploy.go
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/action/actioninvoke.go
  cli/ioctl/cmd/action/actiontransfer.go
  cli/ioctl/cmd/alias/aliasremove.go
  cli/ioctl/cmd/alias/aliasset.go
  cli/ioctl/cmd/bc/bcblock.go
  cli/ioctl/cmd/bc/bcinfo.go
  cli/ioctl/cmd/config/configsetget.go
  cli/ioctl/cmd/node/nodedelegate.go
  cli/ioctl/cmd/node/nodereward.go
  cli/ioctl/cmd/update/update.go
  cli/ioctl/cmd/version/version.go
Labels: 0.5.0-rc9, bug

#957 Add alias import/export cmd for ioctl
  cli/ioctl/cmd/alias/alias.go
  cli/ioctl/cmd/alias/aliasexport.go
  cli/ioctl/cmd/alias/aliasimport.go
Labels: enhancement, ioctl

#978 connect to more than 50% of boot node
  p2p/agent.go
Labels: 0.5.0-rc9

#980 Fix dockerfile
  Dockerfile
Labels: 0.5.0-rc9

#966 IOTEX-955 remove return value and introduce read only execution to test framework
  action/protocol/execution/evm/evm.go
  action/protocol/execution/evm/evm_test.go
  action/protocol/execution/protocol.go
  action/protocol/execution/protocol_test.go
  action/protocol/execution/testdata/array-return.json
  action/protocol/execution/testdata/basic-token.json
  action/protocol/execution/testdata/call-dynamic.json
  action/protocol/execution/testdata/changestate.json
  action/protocol/execution/testdata/erc20.json
  action/protocol/execution/testdata/f.value.json
  action/protocol/execution/testdata/factory.json
  action/protocol/execution/testdata/infiniteloop.json
  action/protocol/execution/testdata/mapping-delete.json
  action/protocol/multichain/mainchain/createdeposit.go
  action/protocol/multichain/mainchain/createdeposit_test.go
  action/protocol/rewarding/protocol.go
  action/receipt.go
  api/api.go
  blockchain/blockchain.go
  blockchain/blockdao_test.go
  cli/ioctl/cmd/action/actionhash.go
  explorer/explorer.go
  explorer/explorer_test.go
  explorer/gasstattion.go
  gasstation/gasstattion.go
  indexservice/indexer_test.go
  proto/api/api.proto
  proto/types/action.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/action.pb.go
  test/mock/mock_blockchain/mock_blockchain.go
  tools/executiontester/blockchain/trading.go
Labels: 0.5.0-rc9, breaking change

#975 Consensus node high availability (Part 1): allow consensus node stand-by
  config/config.go
  consensus/consensus.go
  consensus/consensusfsm/context.go
  consensus/consensusfsm/fsm.go
  consensus/consensusfsm/fsm_test.go
  consensus/consensusfsm/mock_context_test.go
  consensus/scheme/noop.go
  consensus/scheme/rolldpos/rolldpos.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/scheme.go
  consensus/scheme/standalone.go
  pkg/ha/ha.go
  server/itx/server.go
  test/mock/mock_consensus/mock_consensus.go
Labels: 0.5.0-rc9, enhancement, feature, ha

#986 Add account ethaddr cmd
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/account/accountethaddr.go
Labels: enhancement

#968 IOTEX-392 Limit action pool size by intrinsic gas instead of num of actions
  actpool/actpool.go
  actpool/actpool_test.go
  config/config.go
  test/mock/mock_actpool/mock_actpool.go
Labels: 0.5.0-rc9

#956 issue: buildcli.sh will make git status dirty
  cli/ioctl/buildcli.sh
Labels: 0.5.0-rc9

#985 Make node speculatively request higher blocks on every block sync interval
  blocksync/blocksync.go
  blocksync/blocksync_test.go
  blocksync/buffer.go
  blocksync/buffer_test.go
Labels: 0.5.0-rc9

#993 Define experimental action and do not process them by default
  action/action.go
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/protocol_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  action/protocol/multichain/subchain/protocol_test.go
  actpool/actpool.go
  actpool/actpool_test.go
  actpool/actqueue_test.go
  api/api_test.go
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/blockvalidator.go
  blockchain/blockvalidator_test.go
  blocksync/blocksync_test.go
  blocksync/buffer_test.go
  chainservice/chainservice.go
  config/config.go
  consensus/scheme/rolldpos/rolldpos_test.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/multichain_test.go
  e2etest/net_test.go
  explorer/explorer_test.go
  test/mock/mock_blockchain/mock_blockchain.go
  tools/minicluster/minicluster.go
Labels: 0.5.0-rc9

#997 fetch account from cached contract first for add balance
  action/protocol/execution/evm/evmstatedbadapter.go
  action/protocol/execution/protocol_test.go
  action/protocol/execution/testdata/reentry-attack.json
  action/protocol/execution/testdata/reentry-attack.sol
Labels: 0.5.0-rc9, bug

#1000 Add an endpoint flag and fix a flag mistake
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/alias/aliasexport.go
  cli/ioctl/cmd/bc/bc.go
  cli/ioctl/cmd/node/node.go
Labels: enhancement

#1002 Update account ethaddr cmd
  cli/ioctl/cmd/account/accountethaddr.go
  cli/ioctl/cmd/alias/alias.go
Labels: enhancement

#1001 add max number of connection limit to http servers
  Gopkg.lock
  pkg/probe/probe.go
  pkg/util/httputil/httputil.go
  server/itx/server.go
  vendor/golang.org/x/net/netutil/listen.go
Labels: v0.5.0-rc10

#1004 Fix ioctl dirty git status in nightly build and remove useless export
  .circleci/config.yml
Labels: invalid

#1007 Add timestamp to actionInfo and return actionHash in SendAction
  api/api.go
  api/api_test.go
  proto/api/api.proto
  proto/types/blockchain.proto
  protogen/iotexapi/api.pb.go
  protogen/iotextypes/blockchain.pb.go
Labels: v0.5.0-rc10

#1012 Enable rate limit in p2p agent
  e2etest/local_actpool_test.go
  p2p/agent.go
Labels: v0.5.0-rc10

#1016 Estimate gas limit and gas price when default for ioctl
  action/claimreward.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionclaim.go
  cli/ioctl/cmd/action/actiondeploy.go
  cli/ioctl/cmd/action/actioninvoke.go
  cli/ioctl/cmd/action/actiontransfer.go
Labels: enhancement

#1015 Set up a range query upper limit in API
  api/api.go
  api/api_test.go
  config/config.go
Labels: v0.5.0-rc10

#1017 Add action source address blacklist in actpool
  actpool/actpool.go
  actpool/actpool_test.go
  config/config.go
Labels: v0.5.0-rc10

#1031 Update usage of ethaddr cmd for ioctl
  cli/ioctl/cmd/account/accountethaddr.go
Labels: ioctl

#1029 Make foundation bonus exclude robot machines
  action/protocol/rewarding/protocol_test.go
  action/protocol/rewarding/reward.go
  action/protocol/rewarding/reward_test.go
Labels: breaking change, v0.5.0-rc10

#1034 fail transfer is the recipient is a contract address
  action/protocol/account/transfer.go
  action/protocol/account/transfer_test.go
  action/transfer.go
  actpool/actpool.go
  state/account.go
Labels: breaking change, v0.5.0-rc10

#1038 IOTEX-1025 update consensus messages
  consensus/scheme/rolldpos/rolldposctx.go
Labels: v0.5.0-rc10

#1045 Expose total balance and available balance and add more rewarding tests
  action/protocol/rewarding/protocol.go
  action/protocol/rewarding/protocol_test.go
  api/api_test.go
Labels: v0.5.0

#1046 Add action deposit cmd for ioctl
  action/depositreward.go
  action/protocol/rewarding/protocol_test.go
  action/rewardmsg_test.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actiondeposit.go
Labels: breaking change, enhancement, ioctl

#1047 Update node reward cmd
  cli/ioctl/cmd/node/nodereward.go
Labels: enhancement, ioctl, v0.5.0

#1051 ioctl connects endpoint with TLS by default and add insecure flag
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/action/actionhash.go
  cli/ioctl/cmd/bc/bc.go
  cli/ioctl/cmd/bc/bcblock.go
  cli/ioctl/cmd/config/config.go
  cli/ioctl/cmd/node/node.go
  cli/ioctl/cmd/node/nodedelegate.go
  cli/ioctl/cmd/node/nodereward.go
  cli/ioctl/cmd/version/version.go
  cli/ioctl/util/util.go
Labels: enhancement, ioctl

#1052 Update ioaddr and p2p versions
  Gopkg.lock
  Gopkg.toml
  explorer/explorer_test.go
  vendor/github.com/iotexproject/go-p2p/Gopkg.lock
  vendor/github.com/iotexproject/go-p2p/p2p.go
  vendor/github.com/iotexproject/iotex-address/.gitignore
  vendor/github.com/iotexproject/iotex-address/README.md
  vendor/github.com/iotexproject/iotex-address/address/address_v1.go
  vendor/github.com/iotexproject/iotex-address/address/address_v1_test.go
  vendor/github.com/iotexproject/iotex-address/address/bech32/bech32_test.go
  vendor/github.com/iotexproject/iotex-address/example.go
  vendor/github.com/ipfs/go-datastore/autobatch/autobatch.go
  vendor/github.com/libp2p/go-libp2p-circuit/Makefile
  vendor/github.com/libp2p/go-libp2p-circuit/README.md
  vendor/github.com/libp2p/go-libp2p-circuit/package.json
  vendor/github.com/libp2p/go-libp2p-circuit/relay.go
  vendor/github.com/libp2p/go-libp2p-circuit/util.go
  vendor/github.com/libp2p/go-libp2p-kad-dht/.travis.yml
  vendor/github.com/libp2p/go-libp2p-kad-dht/Makefile
  vendor/github.com/libp2p/go-libp2p-kad-dht/README.md
  vendor/github.com/libp2p/go-libp2p-kad-dht/go.mod
  vendor/github.com/libp2p/go-libp2p-kad-dht/go.sum
  vendor/github.com/libp2p/go-libp2p-kad-dht/package.json
  vendor/github.com/libp2p/go-libp2p-nat/go.mod
  vendor/github.com/libp2p/go-libp2p-nat/go.sum
  vendor/github.com/libp2p/go-libp2p-peerstore/.travis.yml
  vendor/github.com/libp2p/go-libp2p-peerstore/Makefile
  vendor/github.com/libp2p/go-libp2p-peerstore/README.md
  vendor/github.com/libp2p/go-libp2p-peerstore/interface.go
  vendor/github.com/libp2p/go-libp2p-peerstore/package.json
  vendor/github.com/libp2p/go-libp2p-peerstore/peerinfo.go
  vendor/github.com/libp2p/go-libp2p/Makefile
  vendor/github.com/libp2p/go-libp2p/README.md
  vendor/github.com/libp2p/go-libp2p/go.mod
  vendor/github.com/libp2p/go-libp2p/go.sum
  vendor/github.com/libp2p/go-libp2p/package.json
  vendor/github.com/libp2p/go-nat/.travis.yml
  vendor/github.com/libp2p/go-nat/README.md
  vendor/github.com/libp2p/go-nat/nat.go
  vendor/github.com/libp2p/go-nat/natpmp.go
  vendor/github.com/libp2p/go-nat/package.json
  vendor/github.com/libp2p/go-nat/upnp.go
  vendor/github.com/mmcloughlin/avo/gotypes/components.go
  vendor/github.com/mmcloughlin/avo/operand/checks.go
  vendor/github.com/mmcloughlin/avo/operand/make_const.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/golang.org/x/sys/windows/mkerrors.bash
  vendor/golang.org/x/sys/windows/mkerrors.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zerrors_windows.go
Labels: breaking change, v0.5.0

#1053 Default gas price for ioctl
  cli/ioctl/cmd/action/action.go
Labels: ioctl

#1058 add nonce on transfer failure and add unit tests
  action/protocol/account/transfer.go
  action/protocol/account/transfer_test.go
Labels: breaking change, v0.5.0

#1059 Prevent actions with negative amount and gas price
  action/const.go
  action/protocol/account/transfer.go
  action/protocol/account/transfer_test.go
  action/protocol/execution/protocol.go
  action/protocol/execution/protocol_test.go
  action/protocol/rewarding/admin.go
  action/protocol/rewarding/fund.go
  action/protocol/rewarding/fund_test.go
Labels: breaking change, v0.5.0

#1063 Remove unused variable for ioctl
  cli/ioctl/cmd/account/account.go
  cli/ioctl/cmd/action/action.go
  cli/ioctl/cmd/bc/bc.go
  cli/ioctl/cmd/node/node.go
  cli/ioctl/cmd/version/version.go
Labels: bettereng, ioctl

#1069 Update account delete cmd for ioctl
  cli/ioctl/cmd/account/accountdelete.go
Labels: ioctl

#1064 Print time stamp in action hash cmd for ioctl
  cli/ioctl/cmd/action/actionhash.go
Labels: ioctl

#1079 make sure testing identity set addresses will not be merged with yaml config
  blockchain/genesis/genesis.go
  blockchain/genesis/genesis_test.go
Labels: v0.6.0

#1081 Remove iotex-core/test/assets/ssl/ #1076
  test/assets/ssl/127.0.0.1.crt
  test/assets/ssl/127.0.0.1.csr
  test/assets/ssl/127.0.0.1.key
  test/assets/ssl/README.md
  test/assets/ssl/iotex.io.crl
  test/assets/ssl/iotex.io.crt
  test/assets/ssl/iotex.io.key
Labels: v0.6.0

#1085 Remove JSON RPC related code #1057
  action/protocol/execution/evm/evmstatedbadapter_test.go
  action/protocol/multichain/subchain/protocol.go
  action/protocol/multichain/subchain/protocol_test.go
  blockchain/blockdao_test.go
  chainservice/chainservice.go
  config/config.go
  config/config_test.go
  consensus/consensus.go
  consensus/scheme/rolldpos/rolldpos.go
  consensus/scheme/rolldpos/rolldpos_test.go
  consensus/scheme/rolldpos/rolldposctx.go
  consensus/scheme/rolldpos/subchain.go
  consensus/scheme/rolldpos/subchain_test.go
  e2etest/local_actpool_test.go
  e2etest/local_test.go
  e2etest/multichain_test.go
  explorer/client.go
  explorer/client_test.go
  explorer/explorer.go
  explorer/explorer_test.go
  explorer/gasstattion.go
  explorer/idl/explorer.idl
  explorer/idl/explorer/explorer.go
  explorer/server.go
  explorer/server_test.go
  server/itx/server.go
  server/itx/subchain.go
  test/mock/mock_explorer/mock_explorer.go
Labels: v0.6.0

#1096 Fix unexpected blockchain stop before finishing the contract tests
  action/protocol/execution/protocol_test.go
  action/protocol/multichain/mainchain/protocol_test.go
  action/protocol/multichain/mainchain/startsubchain_test.go
  blockchain/blockchain_test.go
  consensus/consensusfsm/fsm_test.go
  db/trie/trie_test.go
  gasstation/gasstattion_test.go
Labels: v0.6.0

#1102 Fix lint-rich warnings #681 first batch
  Makefile
  action/transfer_test.go
  actpool/actpool_test.go
  api/api.go
  api/api_test.go
  blockchain/blockchain_test.go
  blocksync/blocksync_test.go
  chainservice/chainservice.go
  cli/ioctl/cmd/account/accountimport.go
  consensus/consensusfsm/fsm_test.go
  consensus/scheme/rolldpos/rolldpos.go
  consensus/scheme/rolldpos/rolldpos_test.go
  db/db_badger.go
  db/db_test.go
  state/factory/factory_test.go
  state/factory/statedb.go
Labels: v0.6.0

#1074 bump iotex-election version
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/iotexproject/iotex-election/LICENSE
  vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
  vendor/github.com/iotexproject/iotex-election/committee/committee.go
  vendor/github.com/iotexproject/iotex-election/committee/heightmanager.go
  vendor/github.com/iotexproject/iotex-election/committee/resultcache.go
  vendor/github.com/iotexproject/iotex-election/db/kvstore.go
  vendor/github.com/iotexproject/iotex-election/pb/election/election.proto
  vendor/github.com/iotexproject/iotex-election/types/candidate.go
  vendor/github.com/iotexproject/iotex-election/types/result.go
  vendor/github.com/iotexproject/iotex-election/types/resultcalculator.go
  vendor/github.com/iotexproject/iotex-election/types/vote.go
  vendor/github.com/iotexproject/iotex-election/util/util.go
Labels: v0.5.1, v0.6.0

#1097 change default gas config to 1Qev
  config/config.go
  gasstation/gasstattion_test.go
Labels: v0.5.1, v0.6.0

#1077 Fix TestBlockEpochReward sporadic failure
  e2etest/rewarding_test.go
Labels: v0.5.1, v0.6.0

#1093 Cleanup native voting system code #1071 first step
  action/action_test.go
  action/protocol/vote/protocol_test.go
  action/vote_test.go
  actpool/actioniterator/actioniterator_test.go
  actpool/actpool_test.go
  actpool/actqueue_test.go
  api/api_test.go
  blockchain/blockvalidator_test.go
  indexservice/indexer_test.go
  state/factory/factory_test.go
Labels: v0.6.0
